[tool.poetry]
name = "service_queue"
version = "2.2.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
