name: HDC ci/cd pipeline consumer

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'consumer/**'
  pull_request:
    branches:
      - main
    paths:
      - 'consumer/**'

jobs:
  run_tests_hdc:
    uses: PilotDataPlatform/pilot-hdc-ci-tools/.github/workflows/run_tests.yml@main
    with:
      min_coverage_percent: 0
      coverage_target: 'consumer'
      poetry_directory: 'consumer'
      pytest_directory: 'consumer'
    secrets: inherit

  build_and_publish_hdc:
    needs: [run_tests_hdc]
    uses: PilotDataPlatform/pilot-hdc-ci-tools/.github/workflows/build_and_publish.yml@main
    with:
      matrix_config: '["consumer"]'
      service_name: 'consumer'
      path_to_dockerfile: './consumer/Dockerfile'
      path_to_pyproject: './consumer/pyproject.toml'
      registry_subpath: 'queue'
    secrets: inherit

  update_gitops_hdc:
    needs: [build_and_publish_hdc]
    if: github.event_name != 'pull_request'
    uses: PilotDataPlatform/pilot-hdc-ci-tools/.github/workflows/update_gitops_versions.yml@main
    with:
      service_key: queue-consumer
      image_tag: "consumer-${{ needs.build_and_publish_hdc.outputs.app_version }}"
      versions_file: clusters/dev/apps/queue-consumer/values.yaml
      yaml_path: '.queue-service.image.tag'
    secrets: inherit
